"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import dj_database_url
from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta

# load .env into system environment
load_dotenv()  
ENV = os.getenv("ENV", "DEV")  # DEV / PROD

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY=os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
# ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

# For deployment 
DEBUG = os.getenv("DEBUG", "False") == "True"
# Allowed Hosts
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "*").split(",")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    'rest_framework',
    'corsheaders',
    "rest_framework_simplejwt.token_blacklist",  # enable blacklist
    # Local
    'apps.users',
    'apps.catalog',
    'apps.cart',
    'apps.wishlist',
    'apps.roles',
    'apps.payments',
    'apps.orders',
    'apps.frontend_logs',
    'drf_spectacular',          # API schema and docs
    'drf_spectacular_sidecar',      # API schema and docs
    'django_filters',
    'cloudinary',
    'cloudinary_storage',
    

]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "core.utils.logger.middleware.APILogMiddleware",            # custom logging middleware
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                'django.template.context_processors.debug',
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

# Database
DATABASES = {
    "default": dj_database_url.config(
        default=os.getenv("DATABASE_URL", f"sqlite:///{BASE_DIR / 'db.sqlite3'}"),
        conn_max_age=600,  # Keeps DB connections alive for 10 minutes
        ssl_require=False, # Set to True if Render forces SSL
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "users.User"
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_RATES": {
        'anon': '1000/day',   # anonymous users can make 1000 requests per day
        'user': '5000/day',   # logged-in users can make 5000 requests per day
        "frontend_logs": "60/min",
    },
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend',
                                'rest_framework.filters.SearchFilter',
                                'rest_framework.filters.OrderingFilter'],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": False,                 # rotation
    "BLACKLIST_AFTER_ROTATION": False,              # blacklist old refresh
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# CORS/CSRF (dev-friendly; tighten for prod)
# CORS_ALLOW_ALL_ORIGINS = True

# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",  # Vite dev server
# ]
CORS_ALLOWED_ORIGINS = os.getenv("CORS_ALLOWED_ORIGINS", "").split(",")
# Allow all origins for development purposes
CORS_ALLOW_CREDENTIALS = True

# CSRF_TRUSTED_ORIGINS = ["http://localhost:5173"]
CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",")

CSRF_COOKIE_NAME = "csrftoken"
CSRF_COOKIE_HTTPONLY = False  # must be readable by JS to send header
CSRF_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SECURE = ENV == "PROD"

SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = ENV == "PROD"

# Cookie flags for refresh cookie we will set manually in views
SECURE_COOKIES = ENV == "PROD"



STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET")
RAZORPAY_KEY_ID = os.getenv("RAZORPAY_KEY_ID")
RAZORPAY_KEY_SECRET = os.getenv("RAZORPAY_KEY_SECRET")

# =============================
# Logging (custom Smart Logger)
# =============================

# ---- Logging Toggles ----
LOGGING_ENABLED = os.getenv("LOGGING_ENABLED", "true").lower() == "true"
LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO").upper()
LOG_FILE = os.getenv("LOG_FILE", "logs/app.log")

BASE_DIR = Path(__file__).resolve().parent.parent.parent
LOG_FILE_PATH = os.path.join(BASE_DIR, LOG_FILE)
FRONTEND_LOGS_ENABLED = os.getenv("FRONTEND_LOGS_ENABLED", "false").lower() == "true"

# Ensure logs directory exists
os.makedirs(os.path.dirname(LOG_FILE_PATH), exist_ok=True)

# ---- Choose handler based on DEV/PROD (Windows-safe) ----
if DEBUG:
    # Development (Windows) → avoid rotation
    FILE_HANDLER_CLASS = "logging.FileHandler"
    FILE_HANDLER_PARAMS = {}
else:
    # Production (Linux/Render) → enable rotation
    FILE_HANDLER_CLASS = "logging.handlers.RotatingFileHandler"
    FILE_HANDLER_PARAMS = {
        "maxBytes": 1024 * 1024 * 5,  # 5 MB
        "backupCount": 5,
    }

# ---- Final Logging Config ----
if LOGGING_ENABLED:
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "default": {
                "format": "{levelname} {asctime} {name} {message}",
                "style": "{",
            },
        },
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "formatter": "default",
                "level": LOG_LEVEL,
            },
            "file": {
                "class": FILE_HANDLER_CLASS,
                "filename": LOG_FILE_PATH,
                "formatter": "default",
                "level": LOG_LEVEL,
                **FILE_HANDLER_PARAMS,  # will be empty in dev
            },
        },
        "root": {
            "handlers": ["console", "file"],
            "level": LOG_LEVEL,
        },
        "loggers": {
            "django": {
                "handlers": ["console", "file"],
                "level": "INFO",   # keep framework noise low
                "propagate": False,
            },
            "django.request": {
                "handlers": ["console", "file"],
                "level": "ERROR",  # only log request errors
                "propagate": False,
            },
            # ✅ your custom logs will use setup_logger() and still write to same file
            "app": {  # any logger named 'app' or child
                "handlers": ["console", "file"],
                "level": LOG_LEVEL,
                "propagate": False,
            },
        },
    }
else:
    # Logging disabled → only critical errors shown
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "handlers": {
            "null": {
                "class": "logging.NullHandler",
            },
        },
        "root": {
            "handlers": ["null"],
            "level": "CRITICAL",
        },
    }
# ============================= Swagger / API Docs =============================
# You can customize Title, Description, Version later.

SPECTACULAR_SETTINGS = {
    'TITLE': 'E-commerce API',
    'DESCRIPTION': 'API documentation for the full-stack e-commerce application.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,

    # ✅ This ensures authentication classes are included in schema
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication'
    ],

    # ✅ Optional but okay to include
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated'
    ],

    # ✅ REQUIRED: Tell schema about security globally
    'SECURITY': [
        {'bearerAuth': []}
    ],

    # ✅ REQUIRED: Define security scheme correctly
    'SECURITY_SCHEMES': {
        'bearerAuth': {
            'type': 'http',
            'scheme': 'bearer',
            'bearerFormat': 'JWT',
        },
    },

    # OPTIONAL (keep or remove, doesn’t matter)
    'COMPONENT_SPLIT_REQUEST': True,
}

# Static Files (important for Render)
#STATIC_URL = "static/"
#STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Static Files (important for Render)
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")

# ============================================
# 🌥️ Cloudinary Media Configuration
# ============================================
import cloudinary
import cloudinary.uploader
import cloudinary.api

cloudinary.config(
    cloud_name=os.getenv("CLOUDINARY_CLOUD_NAME"),
    api_key=os.getenv("CLOUDINARY_API_KEY"),
    api_secret=os.getenv("CLOUDINARY_API_SECRET"),
    secure=True
)

# Cloudinary credentials (loaded from .env)
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
    'MEDIA_TAG': 'ecommerce',  # optional grouping tag
    'STATICFILES_MANIFEST_ROOT': 'staticfiles',
}

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'



