# Generated by Django 5.2.5 on 2025-09-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roles", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="roles",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="roles.role"
            ),
        ),
    ]
